# Generated by Django 3.2.5 on 2021-07-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='thumbnail')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('curated_time', models.DateTimeField(auto_now_add=True)),
                ('github_link', models.URLField()),
                ('website_link', models.URLField()),
                ('category', models.ManyToManyField(related_name='category', to='portfolio.Category')),
            ],
        ),
    ]
